FROM ubuntu:yakkety

RUN export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y \
    aspcud \
    build-essential \
    darcs \
    git \
    gconf2 \
    gconf-service \
    gvfs-bin \
    iputils-ping \
    libasound2 \
    libgmp-dev \
    libgtk2.0-0 \
    libnotify4 \
    libnss3 \
    libxkbfile1 \
    libxss1 \
    libxtst6 \
    m4 \
    mercurial \
    net-tools \
    pkg-config \
    python \
    unzip \
    wget \
    xdg-utils \
    xterm \
    zlib1g-dev \
  && wget \
      https://github.com/atom/atom/releases/download/v1.12.6/atom-amd64.deb \
  && dpkg -i atom-amd64.deb \
  && rm atom-amd64.deb \
  && useradd -d /home/atom -m atom \
  && mkdir -p /home/atom/databox-store-hls-video \
  && chown -R atom:atom /home/atom \
  && wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh \
      -O - | sh -s /usr/local/bin

USER atom

WORKDIR /home/atom

RUN opam init -y -a --comp=4.04.0

RUN eval `opam config env` \
  && opam install \
      merlin \
      ocp-indent

RUN apm install file-types \
    language-docker \
    language-ocaml \
    linter \
    ocaml-merlin \
    ocaml-indent

RUN eval `opam config env` \
  && opam install \
      atdgen.1.10.0 \
      cohttp.0.21.0 \
      config-file.1.2 \
      git-unix.1.7.1 \
      irmin.0.12.0 \
      irmin-watcher.0.2.0 \
      logs.0.6.2 \
      lwt.2.5.2 \
      nocrypto.0.5.3 \
      oasis.0.4.7 \
      odate.0.5 \
      ounit.2.0.0 \
      re2.113.33.00+4.03 \
      uri.1.9.2 \
      uuidm.0.9.6 \
      yojson.1.3.2

WORKDIR /home/atom/databox-store-hls-video

CMD eval `opam config env` \
  && cd /home/atom/databox-store-hls-video/src/lib-databox \
  && atdgen -t databox_directory_types.atd \
  && atdgen -j databox_directory_types.atd \
  && cd /home/atom/databox-store-hls-video/src/store \
  && atdgen -t datastore_types.atd \
  && atdgen -j datastore_types.atd \
  && cd /home/atom/databox-store-hls-video \
  && oasis setup -setup-update dynamic \
  && ocaml setup.ml -configure \
  && /bin/bash --login
